@echo off
echo Starting UB-WaveX...
echo.
echo Checking MySQL service...
sc query MySQL80 | find "RUNNING" >nul
if %errorlevel% neq 0 (
    echo MySQL service is not running. Starting...
    net start MySQL80
)
echo.
echo Launching application...
call npm start
